export const CLIENT_ID = 'client_id=f4323c6f7c0cd73d2d786a2b1cdae80c';
export const SONGS_FETCH_SUCCESS = 'GET_SONGS_DATA';
export const FETCH_ERROR = 'FETCH_ERROR';
export const SONGS_LOADING = 'DATA_LOADING';
export const ROOT_URL = ' http://api.soundcloud.com/tracks?';
export const GET_GENRES = 'GET_GENRES';
export const GET_SONGS_BY_GENRE = 'GET_SONGS_BY_GENRE';
export const GET_MORE_SONGS = 'GET_MORE_SONGS';
export const MORE_SONGS_LOADING = 'MORE_SONGS_LOADING';
export const GET_PLAYER_SOURCES = 'GET_PLAYER_SOURCES';
export const DEFAULT_IMG = 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQ9eiIcFl-B4_Iis6J-NLR2PTCoNROksF2CJ9jHSk9A2UmYHJd9RJq6';
export const GET_PREV_SONG = 'GET_PREV_SONG';
export const GET_NEXT_SONG = 'GET_NEXT_SONG';
export const AUTH_USER = 'AUTH_USER';
export const GET_SEARCH_VALUE = 'GET_SEARCH_VALUE';